export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_MAX_PRICE = 'CHANGE_MAX_PRICE';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const BASKET_COUNT_INCREMENT = 'BASKET_COUNT_INCREMENT';
export const BASKET_COUNT_DECREMENT = 'BASKET_COUNT_DECREMENT';
